### ISSUE TITLE
Hi, Lkurzyniec, How to set sqllite or mysql connection

### ISSUE THREAD

**Issue by dream811** [lkurzyniec/YellowNotes#14]
Thanks for your perfect work!
I hope to know how to connect sqllite or mysql with db configuration.
If you have any sample config file, please kindly share  for me.
Thanks again.

**Comment by lkurzyniec** [comment]
Hi @dream811! Unfortunately, I don't have and valid and/or up-to-date configuration for both sqllite and mysql. Last time I worked with mysql in EF6 around 6 years ago. For sure, you have to google below things:
- how to connect to database with EF6 using DbContext
- how to utilize mysql connector (https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework60.html)

**Comment by dream811** [comment]
Thanks a lot!
